name: Build, Test, and Auto-Fix
on:
  push:
    branches: [ main, master ]
permissions:
  contents: write
  pull-requests: write
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js (change if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install, Build, and Test
        id: build_step
        continue-on-error: true
        run: |
          # عدّل هذه الأوامر لتناسب مشروعك
          if [ -f "package.json" ]; then npm install; fi
          if [ -f "package.json" ] && grep -q '"build"' package.json; then npm run build; fi
          if [ -f "package.json" ] && grep -q '"test"' package.json; then npm test; fi
      - name: 🤖 Copilot Auto-Fix on Failure
        if: steps.build_step.outcome == 'failure'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install github/gh-copilot
          gh pr create --title "🤖 Copilot Fix: Build Failed" --body "The build process failed. This PR is a placeholder to notify developers. Please check the Action logs for details."
